name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm" # caches dependencies based on package-lock.json

      - name: Install, build, and upload Astro site
        uses: withastro/action@v5
        with:
          node-version: 20
          cache: "npm"